"""Pydantic models for the slide and infographic pipelines.

Models are grouped by pipeline in submodules (slide, infographic). This
package re-exports every public class so existing imports
(``from polyptych.models import Task1Output``) continue to work.
"""

from .slide import (
    # Task 1
    GenreParameters,
    SignalDetected,
    Task1Output,
    # Task 2
    SectionAnalysis,
    QuotablePassageQualities,
    QuotablePassage,
    DominantMetaphor,
    SecondaryMetaphor,
    MetaphorInventory,
    EmotionalArc,
    KeyConcept,
    ConceptDistinction,
    ConceptRelation,
    RichConcept,
    ConceptArchitecture,
    StructuralAnalysis,
    SceneBeat,
    CharacterSheet,
    Task2Output,
    # Task 3
    SlideSequenceItem,
    ArcVisualization,
    Task3Output,
    # Task 4
    HeadlineContent,
    SubheadlineContent,
    BodyTextContent,
    QuoteContent,
    SlideAllocation,
    Task4Output,
    # Task 5
    BackgroundSpec,
    HeadlineTypography,
    BodyTypography,
    QuoteTypography,
    Typography,
    ColorSymbol,
    ColorPalette,
    Motif,
    EnvironmentalMotif,
    LayoutPreferences,
    VisualStyle,
    SpecialTechnique,
    DesignSystem,
    Task5Output,
    # Task 6
    SlideContent,
    SlideLayout,
    ImageSpec,
    ColorUsage,
    SlideVisual,
    ArcPosition,
    SlideSpec,
    Task6Output,
    # Task 7
    ImagePromptSections,
    GenerationNotes,
    ImagePrompt,
    ImagePromptDraft,
    SlideImagePrompt,
    SlideImagePromptDraft,
    Task7Draft,
    Task7Output,
)

from .infographic import (
    InfographicKeyPoint,
    InfographicRelationship,
    VisualizableData,
    ContentStructure,
    TaskI0Output,
    InfographicSection,
    InfographicColorPalette,
    TaskI1Output,
    InfographicVariant,
    TaskI2Output,
    I2PromptIssue,
    TaskI2Critique,
)


__all__ = [
    # Slide
    "GenreParameters",
    "SignalDetected",
    "Task1Output",
    "SectionAnalysis",
    "QuotablePassageQualities",
    "QuotablePassage",
    "DominantMetaphor",
    "SecondaryMetaphor",
    "MetaphorInventory",
    "EmotionalArc",
    "KeyConcept",
    "ConceptDistinction",
    "ConceptRelation",
    "RichConcept",
    "ConceptArchitecture",
    "StructuralAnalysis",
    "SceneBeat",
    "CharacterSheet",
    "Task2Output",
    "SlideSequenceItem",
    "ArcVisualization",
    "Task3Output",
    "HeadlineContent",
    "SubheadlineContent",
    "BodyTextContent",
    "QuoteContent",
    "SlideAllocation",
    "Task4Output",
    "BackgroundSpec",
    "HeadlineTypography",
    "BodyTypography",
    "QuoteTypography",
    "Typography",
    "ColorSymbol",
    "ColorPalette",
    "Motif",
    "EnvironmentalMotif",
    "LayoutPreferences",
    "VisualStyle",
    "SpecialTechnique",
    "DesignSystem",
    "Task5Output",
    "SlideContent",
    "SlideLayout",
    "ImageSpec",
    "ColorUsage",
    "SlideVisual",
    "ArcPosition",
    "SlideSpec",
    "Task6Output",
    "ImagePromptSections",
    "GenerationNotes",
    "ImagePrompt",
    "ImagePromptDraft",
    "SlideImagePrompt",
    "SlideImagePromptDraft",
    "Task7Draft",
    "Task7Output",
    # Infographic
    "InfographicKeyPoint",
    "InfographicRelationship",
    "VisualizableData",
    "ContentStructure",
    "TaskI0Output",
    "InfographicSection",
    "InfographicColorPalette",
    "TaskI1Output",
    "InfographicVariant",
    "TaskI2Output",
    "I2PromptIssue",
    "TaskI2Critique",
]
